### ISSUE TITLE
Remote rejected authentication

### ISSUE THREAD

**Issue by adrien3d** [cargo-generate/cargo-generate#1005] opened 2023-08-12 01:39 UTC
**Describe the bug**
Cannot generate from public repository

**To Reproduce**
While trying to 
```
cargo generate \
    --git https://github.com/knurling-rs/app-template \
    --branch main \
    --name rs-nrf-firmware
```

on my Mac OS 13.5 M1, with rustc 1.71.1 (eb26296b5 2023-08-03) I have the following error:
```
Error: Please check if the Git user / repository exists.

Caused by:
    remote rejected authentication: Failed getting response; class=Ssh (23); code=Auth (-16)
```

**Comment by stappersg** [comment] 2023-08-12 13:55
Works for me
```text
stappers@paddy:~
$ cd /tmp
stappers@paddy:/tmp
$ cargo generate \
    --git https://github.com/knurling-rs/app-template \
    --branch main \
    --name rs-nrf-firmware
🔧   Destination: /tmp/rs-nrf-firmware ...
🔧   project-name: rs-nrf-firmware ...
🔧   Generating template ...
🔧   Moving generated files into: `/tmp/rs-nrf-firmware`...
Initializing a fresh Git repository
✨   Done! New project created /tmp/rs-nrf-firmware
stappers@paddy:/tmp
$ lsb_release --all
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
stappers@paddy:/tmp
$ 
```

So this might be a _"Mac OS 13.5 M1"_ thingy,  not a _"rustc 1.71.1"_ thing.
Thing worth to report by the issue reporter:  `cargo generate --version` and which libraries it has linked.

```text
stappers@paddy:/tmp
$ cargo generate --version
cargo generate-generate 0.18.3
stappers@paddy:/tmp
$ ldd ~/.cargo/bin/cargo-generate 
	linux-vdso.so.1 (0x00007ffe7bcc4000)
	libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x00007ff7203f8000)
	libcrypto.so.3 => /lib/x86_64-linux-gnu/libcrypto.so.3 (0x00007ff71f600000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ff71fbe1000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff71fbc1000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff71fae2000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff71f41f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff7204c1000)
stappers@paddy:/tmp
$ 
```

Hmm,  `libgit2` is **not** in the output of `ldd` ...

**Comment by adrien3d** [comment] 2023-08-17 02:21
Do you have any idea on how I can solve this issue?

**Comment by stappersg** [comment] 2023-08-17 05:09
> Thing worth to report by the issue reporter: `cargo generate --version` and which libraries it has linked.

**Comment by sassman** [comment] 2023-08-17 05:48
> Do you have any idea on how I can solve this issue?

The issue Template asks very specific question about your local git config that is good to check first.

I suggest to go thru the issue template and check your git config.

In your case is suspect a http to ssh rewrite rule is in place and maybe passphrase protected ssh keys.

**Comment by saheljalal** [comment] 2023-09-01 04:18
Same problem for me:
```sh
> cargo generate --git https://github.com/rustwasm/wasm-pack-template --name hello-rust-wasm

Error: Please check if the Git user / repository exists.

Caused by:
    remote rejected authentication: Failed getting response; class=Ssh (23); code=Auth (-16)
```

**Comment by sassman** [comment] 2023-09-01 10:10
Folks, this is not a bug.

You have to check your git configuration.
Try it on a blank machine with no custom git / ssh configuration and you will see it works.

For any reasonable investigation you need to dig into your local git config and share all your custom adjustments.

**Comment by sassman** [comment] 2023-09-01 10:24
Duplicate of #874

**Closed by sassman** 2023-09-01 10:24 UTC
Labels: Type: Bug
