### ISSUE TITLE
`cargo generate` command does nothing, maybe related to `zlib1.dll`?

### ISSUE THREAD

**Issue by tana** [cargo-generate/cargo-generate#808] opened 2022-11-27 16:56 UTC
**Describe the bug**
When I ran a `cargo generate` command on Windows PowerShell, it exited immediately with no console or file output.
Similarly, `cargo help generate` or `cargo generate --version` also terminated without any output.

**make sure you**
- [x] I'm on the latest rust version `rustup update`
- [x] I'm on the latest cargo-generate version `cargo install cargo-generate`

**To Reproduce**
1. `cargo generate --git https://github.com/esp-rs/esp-idf-template cargo`
2. output it generated.. : nothing
3. See error

**Expected behavior**
I expected it asks project name, settings, etc. and create a directory containing a new Rust project.

**Screenshots**
![image](https://user-images.githubusercontent.com/342768/204148542-e0bd03d8-3a4e-4452-a62e-8a8af5f1c52b.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home 
 - Version: 21H2
 - Build tools: msvc
 - Shell: powerShell
 - `rustc --version`: `rustc 1.65.0 (897e37553 2022-11-02)`
 - `cargo generate --version`: Nothing was displayed. Version was `v0.17.3`.

**Additional context**
For your information, when I checked DLL dependencies of `cargo-generate.exe` binary with [Dependencies](https://github.com/lucasg/Dependencies) (Windows equivalent of `ldd`), `zlib1.dll`, which `cargo-generate.exe` depends, was not found in the system.
Double-clicking the exe file on the Explorer showed an error that `zlib1.dll` was not found.

As a workaround, building zlib and putting the resultant DLL along with `cargo-generate.exe` as `zlib1.dll` fixes the problem. However, it seems weird.

**Comment by sassman** [comment] 2023-01-07 16:29
@tana this seems to be an old known and also fixed cargo issue rust-lang/cargo/issues/3415

Maybe you can try a `rustup update`?
Could you also fire a `cargo --version` to see if that at least would work (without the .ddl placement in the same folder)

**Comment by tana** [comment] 2023-01-08 16:16
Thank you for your reply. I didn't thought it was a problem of Cargo.
I ran `rustup update` but `cargo-generate --version` still displays nothing (without DLL workaround).
`cargo --version` succeeded even before `rustup update`.
It displayed `cargo 1.66.0 (d65d197ad 2022-11-15)`. I think this is quite recent version.

**Comment by asuper0** [comment] 2023-07-12 16:44
I meet the same error, check the dependencies and found that it's missing zlib1.dll. 
I just copy a zlib1.dll with version 1.2.12.0 from my vcpkg folder, then the generate could work.

**Comment by sassman** [comment] 2023-07-22 21:12
I suspect this is a duplicate of #984
The solution that worked there was: 

> I resolved the issue. After re-installing the zlib library and add them into the path, I also did a restart of my mac. Now the library is linked and cargo generate does not have issue anymore.

**Closed** 2023-07-22 21:12 UTC
Labels: Type: Bug
