### ISSUE TITLE
cargo install cargo-generate failed E0658 on MacBook Pro M1 2020 MacOS Monterey 12.3.1, rustc 1.59.0 (9d1b2106e 2022-02-23)

### ISSUE THREAD

**Issue by AshwinSundar** [cargo-generate/cargo-generate#631] opened 2022-06-08 04:02 UTC
I'm attempting to install cargo-generate on MacBook Pro (M1 2020) running MacOS Monterey 12.3.1, rustc 1.59.0 (9d1b2106e 2022-02-23). I get the following error: 

```
error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
  --> /Users/ashwin/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-generate-0.14.0/src/hooks/mod.rs:19:6
   |
19 | impl<F: FnOnce()> CleanupJob<F> {
   |      ^
20 |     pub const fn new(f: F) -> Self {
   |     ------------------------------ function declared as const here
   |
   = note: see issue #57563 <https://github.com/rust-lang/rust/issues/57563> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `cargo-generate` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-generate v0.14.0`, intermediate artifacts can be found at `/var/folders/36/yw6776y506570jjdmxv5rlpc0000gn/T/cargo-installAC5cKA`

Caused by:
  build failed
```

**Comment by sassman** [comment] 2022-06-08 07:11
duplicate of #623, solution is:

> rustup update

**Closed by sassman** 2022-06-08 07:11 UTC
