### ISSUE TITLE
Error: ⛔   Git Error: invalid version 0 on git_proxy_options; class=Invalid (3)

### ISSUE THREAD

**Issue by B4TT3RY** [cargo-generate/cargo-generate#461] opened 2021-09-23 06:03 UTC
Not working after updating to 0.10.0 version.

```
cargo 1.55.0 (32da73ab1 2021-08-23)
cargo-generate 0.10.0
git version 2.33.0
```

**Comment by taurr** [comment] 2021-09-23 06:11
Duplicate of #456

Same reason... it's due to a dependency inside `git2`

**Comment by sassman** [comment] 2021-09-23 08:09
Patch will be released today.

**Comment by sassman** [comment] 2021-09-24 07:06
This should now be solved with v0.10.1

**Comment by TonalidadeHidrica** [comment] 2021-10-09 08:03
@taurr Thanks for the reply!  I'm using `macOS Big Sur 11.6`.  FWIW, `git 2.33.0`, which I currently use, is one installed via Homebrew, located at `/usr/local/bin/git`, while there is another OS-built-in git at `/usr/bin/git` of version `git version 2.30.1 (Apple Git-130)`.   `libgit2` has also been installed via `brew`, whose version is `libgit2: stable 1.3.0`.  I'm not sure there's a system-wide installation of libgit2.

**Comment by taurr** [comment] 2021-10-09 08:29
@TonalidadeHidrica thx, as I tried to explain, you version of `git` itself really doesn't matter - it is not used.
`cargo-generate` uses another Rust dependency called `git2` - which is the one using `libgit2` (at least I think it does - but I don't think it uses the system installed one as most Rust stuff is statically linked).

In other words, the problem lies somewhere in the `git2` rust crate or one of its dependencies. An issue has already been filed there.

**Comment by TonalidadeHidrica** [comment] 2021-10-09 08:32
Oh sorry, I didn't read it well.  So there's nothing we can do other than fixing `git2` crate?

**Comment by taurr** [comment] 2021-10-09 08:44
I'm not even sure it's a `git2` crate specific issue - seems to be a fairly wellknown issue: https://www.google.com/search?q=invalid%20version%200%20on%20git_proxy_options%3B%20class%3DInvalid%20(3)

**Comment by TonalidadeHidrica** [comment] 2021-10-09 14:02
I've not fully understand what you explain, but at least this is the result for `ldd`.  What other information do I need to supply?

```
/Users/user/.cargo/bin/cargo-generate:
        /usr/local/opt/libgit2/lib/libgit2.1.3.dylib (compatibility version 1.3.0, current version 1.3.0)
        /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
        /usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
        /usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
        /usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Comment by sassman** [comment] 2021-10-09 16:05
I just released `v0.10.2`
@TonalidadeHidrica could you pls try to install that newest version and see if this solves your problem too?

**Comment by TonalidadeHidrica** [comment] 2021-10-09 16:36
@sassman It worked without error!  Thanks a lot.

**Comment by sassman** [comment] 2021-10-09 17:12
glad to hear!

**Comment by taurr** [comment] 2021-10-10 07:27
Simply genius - now it **no longer works - again**

To me, this change stops me from using `cargo-generate` as it basically reverts back to the error.

**Comment by TonalidadeHidrica** [comment] 2021-10-10 07:32
@taurr If `v0.10.1` works but `v0.10.2` doesn't, can't you just stick to `.1`?

**Comment by taurr** [comment] 2021-10-10 07:40
Kinda hard to do any development then - especially as I want the other fixes

**Comment by taurr** [comment] 2021-10-10 09:26
bloody annoying - I was messing around with my system installen `libgit2` package.
Updated to `libgit2-git`, lost ability to link anything, degraded back to the `libgit2` package I just had, and after some further fiddling around, I can now build again - only now its against `git2 = "0.13"` without specifying `libgit2` at all.

This error is definitely not easy to neither reproduce, nor to solve.

Is it time for us to work on #67 ???

**Comment by sassman** [comment] 2021-10-10 14:56
Oh my, sorry @taurr for the troubles.

Could you try to update libgit2 (your Systems lib not the crate).

**Comment by taurr** [comment] 2021-10-13 18:02
As I tried to write the other day: I finally got it to work, but I don't know why!

The system installed version somhow inteferred - but after trying out another system installed version (which caused the linker step of `cargo-generate` to fail, why?), I reverted back to my distros default (which is what I started with), and suddenly it worked!

I know `libgit2-sys` should be independent of the system installed version, but reality is; it's not! Somehow, somewhere, they can conflict during development.

**Comment by cbxbiker61** [comment] 2021-11-12 07:06
Interesting...

I had upgraded libgit2 to 1.3.0 from 1.1.1.  That broke my existing cargo install, so I unpacked the previous libgit.so.1.1 with a link to libgit.so.1.  That's when this error condition showed up.  After thinking a bit I decided to symlink libgit2.so.1.3 to libgit.so.1.1 and it built my new cargo version which linked to the new libgit2.so.1.3.  Then I deleted my libgit.so.1.1 stuff.  Kinda weird, and usually you expect things not to work when a bit has been linked to a previous .so version.

**Comment by sassman** [comment] 2022-02-01 13:38
@MathiasKoch 

> cargo generate --git https://github.com/rust-embedded/cortex-m-quickstart
> ⚠️ Unable to load config file: ~/.cargo/cargo-generate.toml
> Error: ⛔ Git Error: invalid version 0 on git_proxy_options; class=Invalid (3)

Is it possible that your `~/.gitconfig` has a `insteadOf` url configured for GitHub https urls?

If so, then your problem refers more to #533, and will be addressed with the next version of cargo-generate

**Comment by jeremyjs** [comment] 2022-04-23 07:13
> @MathiasKoch
> 
> > cargo generate --git https://github.com/rust-embedded/cortex-m-quickstart
> > ⚠️ Unable to load config file: ~/.cargo/cargo-generate.toml
> > Error: ⛔ Git Error: invalid version 0 on git_proxy_options; class=Invalid (3)
> 
> Is it possible that your `~/.gitconfig` has a `insteadOf` url configured for GitHub https urls?
> 
> If so, then your problem refers more to #533, and will be addressed with the next version of cargo-generate

Thank you, I had a similar issue and disabling the `insteadOf` rule solved it for me 👍 

In my case it was this error that was fixed by disabling `insteadOf`:
```
Error: ⛔   Git Error: Failed to retrieve list of SSH authentication methods: Failed getting response; class=Ssh (23); code=Auth (-16)
```

**Comment by sassman** [comment] 2022-04-23 09:22
@jeremyjs @MathiasKoch 

You could re-try the `insteadOf` configuration with cargo-generate >= `v0.13.1`. It should support the correct resolution of the final git server url.

Feedback if it works or not would be appreciated ofc.

**Closed** 2022-06-16 00:29 UTC
