### ISSUE TITLE
report error in windows

### ISSUE THREAD

**Issue by jm-observer** [cargo-generate/cargo-generate#619] opened 2022-06-02 04:00 UTC
hello, i use in windows, and it report the error:

```
PS D:\hpmq> cargo generate --git http://git.netfuse.cn/iiot-pub/hpmq-wasi-template.git
Error: 拒绝访问。 (os error 5)
```

the reason for this is https://github.com/XAMPPRocky/remove_dir_all/issues/7

i think not remove the .git folder, in turn not to copy .git to project's folder can avoid this problem?

**Comment by 762SPR** [comment] 2022-06-02 08:40
I am having what I believe to be the same issue, and discussed it with some people on the Rust Embedded matrix channel who were able to replicate the issue. 

The problem seems to occur on Windows machines (I am on windows 10) when using cargo generate on a remote template. I tested with a github template [From here](https://github.com/knurling-rs/app-template)

`cargo generate 
    --git https://github.com/knurling-rs/app-template 
    --branch main 
    --name my-app`

The current workaround we found was to manually clone the template and run generate locally. Hope this helps!

**Comment by sassman** [comment] 2022-06-02 18:28
unfortunately on windows 11 for arm I was not able to reproduce this problem.

**Comment by 762SPR** [comment] 2022-06-03 01:17
> I vaguely remember having that issue reproducible. The solution was very stupid, a little waiting time after the `git clone` before the recursive remove was doing the trick back then.
> 
> So [this code](https://github.com/cargo-generate/cargo-generate/blob/main/src/git/mod.rs#L148) should actually take care of the mess.
> 
> Did you actually get the warning message below?
> 
> ```rust
> warn!("Git history cleanup failed with a windows process blocking error. [Retry in {:?}]", wait_for);
> ```
> 
> Update: which cargo-generate version do you folks use?

Version was the latest, I even forced a fresh install with cargo when I was having problems.

I do recall getting some error relating to windows blocking operation where it would retry after a second or two. Sometimes it would take several retries but would always result in the permission denied/ os error 5 eventually.

This would happen maybe 20% of the time, it would usually just go straight to permission denied.

**Comment by jm-observer** [comment] 2022-06-03 08:58
i try again in other pc and it also report error. i had commited a pull(https://github.com/cargo-generate/cargo-generate/pull/621),  It should be more intuitive to look at the code

**Comment by sassman** [comment] 2022-06-04 13:20
#621 should solve this, and will be released soon

**Closed by sassman** 2022-06-04 13:20 UTC
