### ISSUE TITLE
Liquid silently ignores a template variable in github actions workflow file

### ISSUE THREAD

**Issue by AliSajid** [cargo-generate/cargo-generate#765] opened 2022-10-17 18:05 UTC
**Describe the bug**
I am trying to build a convenience etemplate for what is planned to be a project involving a couple dozen CLIs. I have added a bunch of things including github action workflows with liquid variables. The template can be found [here](https://github.com/AliSajid/rust_cli_template). However, cargo generate does not process the github action template

**make sure you**
- [X] I'm on the latest rust version `rustup update`
- [X] I'm on the latest cargo-generate version `cargo install cargo-generate`

**To Reproduce**
1. `cargo generate AliSajid/rust_cli_template`
2. Generated Project
3. Variable substitution not done in github action files

**Expected behavior**
Liquid variable substitution in the github action files

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 12.6
 - Build tools: gcc
 - Shell: zsh
 - `rustc --version`: rustc 1.64.0 (a55dd71d5 2022-09-19)
 - `cargo generate --version`: cargo-generate 0.16.0

**Comment by taurr** [comment] 2022-11-26 20:18
'cargo-generate' does not process *anything* inside the '.git' folder - currently by design.

Within the current set of features, you'd have to use another foldername, and have the user rename/move the folder.

**Comment by ximon18** [comment] 2022-11-26 21:34
I have the same problem. This is about the .github folder, NOT the .git folder.

**Comment by taurr** [comment] 2022-11-29 21:18
That's funny, cause I just expanded a Github CI workflow in the correct `.github` folder using this template: https://github.com/taurr/rust-template-rs/tree/main/Snippets.../Github%20Specific

Not only does it expand the `{{project-name}}` placeholder within the file - it also renames it according to the project name given.

**Comment by AliSajid** [comment] 2022-11-29 22:11
> That's funny, cause I just expanded a Github CI workflow in the correct `.github` folder using this template: https://github.com/taurr/rust-template-rs/tree/main/Snippets.../Github%20Specific
> 
> Not only does it expand the `{{project-name}}` placeholder within the file - it also renames it according to the project name given.

This is interesting. This apparently uses the sub-template mechanism, while my template does not. I think that might be the issue, where top-level `.git*/` directories are ignored but sub templates are not. I'll play with it and report.

**Comment by ximon18** [comment] 2022-11-30 07:10
That’s indeed interesting.

**Comment by AliSajid** [comment] 2022-12-27 05:35
> That's funny, cause I just expanded a Github CI workflow in the correct `.github` folder using this template: https://github.com/taurr/rust-template-rs/tree/main/Snippets.../Github%20Specific
> 
> Not only does it expand the `{{project-name}}` placeholder within the file - it also renames it according to the project name given.

Thank you @taurr. I ran that. It's interesting that I can generate the project files using a sub-template, just like you mentioned. However, when I use my own template which does not have the .github directory as a sub-template, just a regular part, it does not expand it. I'm really confused right now about that. 

Based on the other repo, my template should be renderable without any problems yet it does not. May you please take a look at my repo and see if I have grossly misunderstood something? Many thanks.

**Comment by taurr** [comment] 2023-01-07 09:55
@AliSajid I believe it is some of the syntax in `ci.yaml.liquid` that doesn't sit well with the `liquid` crate.
If you remove all but your variable substitutions you will notice that the substitutions do work - or rather, they should!

Looking further at your template; it uses the GitHub syntax `${{steps.result.outputs.result}}`. Liquid **will see this as a variable `steps.result.outputs.result` that it needs to substitute**. As liquid don't know that variable, it fails (and it fails saying so in the API too, so `cargo-generate` doesn't know it failed!).

The way to work around this issue is a little tricky, but the best I've found is to use the syntax:
```rhai
${{ "steps.result.outputs.result" | prepend: "{{" | append: "}}" }}
```

For furtex capabilities, see [Liquid syntax](https://shopify.github.io/liquid/)

I'm closing the issue as this is not a bug. I'll also create a new one as the biggest issue here is lack of documentation, or writing a FAQ entry (can't remember if `cargo-generate` has a FAQ somewhere)

**Closed by taurr** 2023-01-07 09:55 UTC
Labels: Type: Enhancement

**Comment by taurr** [comment] 2023-01-07 10:23
Please also see #843
