### ISSUE TITLE
'Failed to authenticate SSH session' when cloning from template using ssh.

### ISSUE THREAD

**Issue by hgaiser** [cargo-generate/cargo-generate#470] opened 2021-09-29 15:30 UTC
Running the following `cargo generate` command failed because I am trying to use ssh authentication. Note that this does work when using https, however I would like to use ssh to generate from a private repository.

```
$ cargo generate --git git@github.com:rust-embedded/cortex-m-quickstart
⚠️   Unable to load config file: /home/hgaiser/.cargo/cargo-generate.toml
💡   Using private key: `$HOME/.ssh/id_rsa` for git-ssh checkout
Error: ⛔   Git Error: Failed to authenticate SSH session: Unable to extract public key from private key file: Wrong passphrase or invalid/unrecognized private key file format; class=Ssh (23)
✗ - status code 1
```

**Comment by hgaiser** [comment] 2021-09-29 15:47
> Is your ssh key passphrase protected?

Yes it is. Is this not supported?

**Comment by sassman** [comment] 2021-09-29 16:09
Unfortunately not.
So this is a duplicate of #384

**Closed** 2021-09-29 16:09 UTC

**Comment by hgaiser** [comment] 2021-09-29 16:14
Ah I did see that issue, but didn't see that it also covered password protected keys. Thank you @sassman .
